name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Linting
        run: npm run lint

      - name: Run Formatting Check
        run: npm run prettier:check

      - name: Build Website
        run: npm run build

      - name: Create .nojekyll file
        run: echo "" > ./dist/.nojekyll

      - name: Upload artifact for Pages deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      contents: read

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
